# Generated by Django 4.1.7 on 2023-04-12 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 17, 38, 40, 383627, tzinfo=datetime.timezone.utc)),
        ),
    ]
